### ISSUE TITLE
Quality issues/open externally

### ISSUE THREAD

**Issue by The-furf-of-July** [matjojo/tagrank#4]
There are some problems with the quality of the displayed pictures at times, most notable on large pictures with lots of small text.

I think adding a feature to click on or otherwise select an image could open it in an external program or in hydrus, allowing access to photo viewing controls without having to implement things like zooming and panning yourself.

**Comment by matjojo** [comment]
Ahh, that is not really what I imagined people would use Tagrank for.

I'm going to see if I can do some sort of "OS please open this" request via Qt.

**Comment by matjojo** [comment]
Pushed a solution for this. Press `o` to open both files externally. This should behave the same as if you double-clicked the file in your favourite file explorer, or if you called `open file_path` in your favourite terminal if you are not on windows.
